### ISSUE TITLE
An input can only have one connection

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/gates#3]
![image](https://github.com/EdwardKN/gates/assets/82646131/e3114145-defe-4b66-a491-66596596ae1d)
This should make it so both connections on the left side is connected to the right side. If either of them is enabled, the right side should get enabled. As it stands now, that isn't the case, only the first connection is actually connected.

Either add this functionality, or add an OR operator, which takes 2 input and 1 output.

**Comment by EdwardKN** [comment]
Intentional because you can make your own OR gate. 
<img width="1439" alt="Screenshot 2023-09-06 at 15 16 22" src="https://github.com/EdwardKN/gates/assets/58272561/2d8edef3-2a34-4450-9839-95b2755044f2">
